# Dependabot configuration file
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "clement-brodu"
    assignees:
      - "clement-brodu"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # NuGet packages for main project
  - package-ecosystem: "nuget"
    directory: "/PCTTools"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "clement-brodu"
    assignees:
      - "clement-brodu"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    # Group updates by dependency type
    groups:
      fody:
        patterns:
          - "Fody*"
          - "Costura.Fody"
      build-tools:
        patterns:
          - "GitVersion*"

  # NuGet packages for test project
  - package-ecosystem: "nuget"
    directory: "/PCTTools.Tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "clement-brodu"
    assignees:
      - "clement-brodu"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
      - "tests"

  # NuGet packages for sample project
  - package-ecosystem: "nuget"
    directory: "/PCTTools.Sample"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "clement-brodu"
    assignees:
      - "clement-brodu"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
      - "sample"

  # NuGet packages for app project
  - package-ecosystem: "nuget"
    directory: "/PCTToolsApp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "clement-brodu"
    assignees:
      - "clement-brodu"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
      - "app"